# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chelsea Nam
email: ccnam@colostate.edu
description: "Chelsea Nam's Research and Teaching Website. In this website, you will find her research on Tropical Cyclone Genesis using ensemble model simulaitons, radar observations and reanalyses, and her teaching philsophy and experiences in Atmosperic Sciences"
keywords: "Tropical cyclogenesis, pedagogy, atmospheric science, PhD, colorado state university, hurricane"
baseurl: " " # the subpath of your site, e.g. /blog
url: "https://chelsea-nam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

facebook_url: 'http://facebook.com/themeix'
twitter_url: 'http://twitter.com/themeix_ltd'
github_url: 'http://github.com/themeix'
youtube_url: 'http://youtube.com/themeix'
google_plus_url: 'http://plus.google.com'
pinterest_url: 'http://pinterest.com'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
